name: Main Workflow
on: [ push, pull_request ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.15.1"
      - name: Install dependencies
        env:
          CI: true
        run: npm install
      - name: Run lint
        env:
          CI: true
        run: npm run lint
      - name: Run Test
        env:
          CI: true
        run: npm run test
